package pkg8daysofcoding;
public class Main {
    public static void main(String[] args) {
       
        String teks1 = "hlooo gyss";
        String teks2 = "semangat ngoding nya";
        System.out.println(teks1);
        System.out.println(teks2);
        
        String nama = "christyne alfryna vernanda";
        String prodi ="jurusan teknik informatika";
        String both = nama +" "+ prodi;
        System.out.println(both);
    }
    
}
