package pkg7daysofcoding;
public class Main {
    public static void main(String[] args) {
        /*Char: Digunakan untuk menyimpan satu karakter saja (huruf, angka, atau simbol).
          Biasanya ditulis dengan tanda petik tunggal ' '.
        */
          char jeniskelamin = 'p';
          System.out.println(jeniskelamin);
          
          /*Boolean: Digunakan untuk menyimpan nilai logika:
            true (benar)
            false (salah)
            Sering dipakai dalam percabangan (if, else) dan perulangan.
          */
          boolean mahasiswa = true;
          System.out.println(mahasiswa);
          
          
}
    
}
