package pkg100daysofcoding;
import java.util.Scanner;
public class Main {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        
        System.out.println("masukkan angka1: ");
        int angka1 = input.nextInt();
        System.out.println("masukkan angka2: ");
        int angka2 = input.nextInt();
        
        System.out.println("perkalian = " + (angka1 * angka2));
        System.out.println("pembagian = " + (angka1 / angka2));
                
        
            }
    
}
