package pkg15daysofcoding;
public class Main {
    public static void main(String[] args) {
        //OPERATOR PENJUMLAHAN
        int a = 20;
        int b = 10;
        int hasilTambah = a + b;
        System.out.println("hasil penjumlah  : " + hasilTambah);
        
        
        //OPERATOR PENGURANGAN
        int angka1 = 40;
        int angka2 = 20;
        int hasilKurang = angka1 - angka2;
        System.out.println("hasil pengurangan: " + hasilKurang);
        
        
        
        
    }
    
}
