import java.util.Scanner;
public class Day18Coding {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
           
        //konversi manual = tipe data besar ke kecil
        long n = 100;
        int m = (int)n;
        System.out.println("konversi manual  = "+m);
        
        short o = 50;
        byte p = (byte)o;
        System.out.println("koversi manual = " +p);
        
        double v = 25;
        float z = (float)v;
        System.out.println("koversi manual = " +z);
       

    }

}
