package pkg2daysofcoding;
public class Main {
    public static void main(String[] args) {
        
   String nama;
   int umur;
   float tb;
   
   nama = "christyne alfryna vernanda";
   umur = 18;
   tb = 155.0f ;
   
        System.out.println("hallo gayss");
        System.out.print("perkenalkan");
        System.out.printf(" nama saya: %s, umur: %d, tinggi badan: %.1f", nama, umur, tb);
   
      }
    
}
