package pkgday20coding;
public class Main {
    public static void main(String[] args) {

        //metode value of:
        short angka1 =90; 
        String teks = String.valueOf(angka1);
        System.out.println(teks);
        
        //metode .toString:
        int angka2 = 100;
        String konversi = Integer.toString(angka2);
        System.out.println(konversi);
                
        //metode operator:
        long angka3 = 1000;
        String output = angka3 + "";
        System.out.println(output);
                
        }
    
}
