package pkgday20coding;
public class Main {
    public static void main(String[] args) {
        //metode value of:
        short angka1 =100; 
        String teks = String.valueOf(nilai);
        System.out.println(teks);
        
        //metode .toString:
        int angka2Int = 90;
        String konversi = Integer.toString(angkaInt);
        System.out.println(konversi);
                
        //metode operator:
        long angka3 = 80;
        String output = angka + "";
        System.out.println(output);
                
        }
    
}
