package pkg4daysofcoding;
public class Main {

    public static void main(String[] args) {
        // kode \n digunakan untuk membuat baris baru
        System.out.println("halo\nGuyss");
        
        // kode \t di gunakan untuk mebuat tab atau spasi
        System.out.println("nama:\tChristyne");
        
        // kode \\(backslash) digunakan untuk menampilkan 1 karakter backslash itu sendiri
        System.out.println("nama ig saya: \\christyne_vernanda\\ difollow");
        
        // kode \" (double qoute) digunakan untuk menampilkan tanda kutip ganda.
        System.out.println("hai kak,\"selamat sore!\"");
        
       
     }
    
}
