public class Day54 {
    public static void main(String[] args) {
        
        for (int i = 1; i < 10; i++) {
            if (i == 5) continue;
                System.out.print(i + " ");
               
            }
        System.out.println("\n=========");
            int a = 0;
            while (a < 10){
                a++;
                if (a == 5)continue;
                System.out.println(a);
            }
        }
    }
    
