package pkg6daysofcoding;
public class Main {
    public static void main(String[] args) {
        /*double: (dauble precision floating point number)
        untuk perhitungan yang membutuhkan ketelitian tinggi.
        */
        double tinggiBadan = 155.0;
        System.out.println(tinggiBadan);
        
        /*Float: (floating point number)
        untuk menyimpan angka desimal
        */
        float beratBadan = 46.1f;
        System.out.println(beratBadan);     
    }
    
}
