public class Day84 {

    
    public static void cetakInfo(String nama, String nim, String jurusan) {
        System.out.println("=== DATA MAHASISWA ===");
        System.out.println("Nama    : " + nama);
        System.out.println("NIM     : " + nim);
        System.out.println("Jurusan : " + jurusan);
    }

    public static void main(String[] args) {
        
        cetakInfo("Christyne", "D0225518", "Informatika");
    }
}
